### ISSUE TITLE
This data is F$&*! up

### ISSUE THREAD

**Issue by theroyalbob** [theroyalbob/KSB621-Spring21-AU#6]
We need to take some corrective action on these datasets.

**Comment by theroyalbob** [comment]
There are some (many) indices that include null's throughout many of the variables. I am open to suggestions about how to handle this. The 2 options I see is deleted any index with a null value the other is to set those sets including "null" as_null (or however this is actually coded in R), which will make analysis possible on these numerical fields.

**Comment by gracewelton** [comment]
Do some null values exist with other data in the same row? If this is the case, I think we should leave them and still run the analysis.
